"""Official Madrid LOMLOE curriculum: which subjects are offered at each
grade, from 1º ESO to 2º Bachillerato. Subjects offered as an "either/or"
choice (e.g. Música or Educación Plástica) are listed as separate options.
"""

GRADES = [
    "1º ESO",
    "2º ESO",
    "3º ESO",
    "4º ESO",
    "1º Bachillerato",
    "2º Bachillerato",
]

GRADE_SUBJECTS = {
    "1º ESO": [
        "Lengua Castellana y Literatura",
        "Matemáticas",
        "Lengua Extranjera (Inglés)",
        "Geografía e Historia",
        "Biología y Geología",
        "Tecnología y Digitalización",
        "Educación Física",
        "Música",
        "Educación Plástica, Visual y Audiovisual",
        "Educación en Valores Cívicos y Éticos",
        "Religión",
        "Tutoría",
        "Segunda Lengua Extranjera",
        "Cultura Clásica",
    ],
    "2º ESO": [
        "Lengua Castellana y Literatura",
        "Matemáticas",
        "Lengua Extranjera (Inglés)",
        "Geografía e Historia",
        "Física y Química",
        "Tecnología y Digitalización",
        "Educación Física",
        "Música",
        "Educación Plástica, Visual y Audiovisual",
        "Educación en Valores Cívicos y Éticos",
        "Religión",
        "Tutoría",
        "Segunda Lengua Extranjera",
        "Cultura Clásica",
    ],
    "3º ESO": [
        "Lengua Castellana y Literatura",
        "Matemáticas",
        "Lengua Extranjera (Inglés)",
        "Geografía e Historia",
        "Biología y Geología",
        "Física y Química",
        "Tecnología y Digitalización",
        "Educación Física",
        "Educación en Valores Cívicos y Éticos",
        "Religión",
        "Tutoría",
        "Segunda Lengua Extranjera",
        "Cultura Clásica",
    ],
    "4º ESO": [
        "Lengua Castellana y Literatura",
        "Matemáticas Académicas",
        "Matemáticas Aplicadas a las CCSS",
        "Lengua Extranjera (Inglés)",
        "Biología y Geología",
        "Física y Química",
        "Tecnología y Digitalización",
        "Educación Física",
        "Educación en Valores Cívicos y Éticos",
        "Religión",
        "Tutoría",
        "Segunda Lengua Extranjera",
        "Latín",
        "Economía",
        "Ciencias Aplicadas a la Actividad Profesional",
        "Iniciación a la Actividad Emprendedora y Empresarial",
    ],
    "1º Bachillerato": [
        "Lengua Castellana y Literatura",
        "Matemáticas",
        "Matemáticas Aplicadas a las CCSS",
        "Lengua Extranjera (Inglés)",
        "Filosofía",
        "Biología y Geología",
        "Física y Química",
        "Educación Física",
        "Religión",
        "Tutoría",
        "Segunda Lengua Extranjera",
        "Latín",
        "Griego",
        "Economía",
        "Historia del Mundo Contemporáneo",
        "Literatura Universal",
        "Dibujo Técnico",
        "Dibujo Artístico",
        "Cultura Audiovisual",
        "Volumen",
        "Ciencias de la Computación",
        "Proyecto de Investigación Integrado",
    ],
    "2º Bachillerato": [
        "Lengua Castellana y Literatura",
        "Matemáticas",
        "Matemáticas Aplicadas a las CCSS",
        "Lengua Extranjera (Inglés)",
        "Historia de la Filosofía",
        "Historia de España",
        "Biología y Geología",
        "Física y Química",
        "Religión",
        "Tutoría",
        "Segunda Lengua Extranjera",
        "Latín",
        "Griego",
        "Geografía",
        "Literatura Universal",
        "Dibujo Técnico",
        "Dibujo Artístico",
        "Historia del Arte",
        "Diseño",
        "Volumen",
        "Tecnología e Ingeniería",
        "Ciencias de la Computación",
        "Psicología",
        "Empresa y Diseño de Modelos de Negocio",
        "Proyecto de Investigación Integrado",
    ],
}
